(in-package :sykobot)

(defproto interpreter-bot ((proto 'command-bot))
  ((people-to-interpret nil)))

(defreply init-sheep :after ((bot (proto 'interpreter-bot)) &key)
  (setf (people-to-interpret bot) nil))

(defcommand interpret ("(\\S+)\\s*into\\s*(\\S+)" nick output-lang)
  "Syntax: 'interpret <output-lang> into <lang>' - Turns on automatic translation of ~
everything <nick> says into <output-lang>. <output-lang> should be a two letter language ~
specifier. Use 'nointerpret <nick>' to stop it."
  (let ((lang (cond ((> 2 (length output-lang))
		     (cdr (assoc output-lang *language-codes* :test #'string-equal)))
		    ((= 2 (length output-lang))
		     output-lang)
		    (t "en"))))
    (setf (alref nick (alref *channel* (people-to-interpret *bot*))) lang)
    (build-string "Very well, I'll translate everything ~A says into ~A" nick lang)))

(defcommand nointerpret ("(.+)" nick)
  "Syntax: 'nointerpret <nick>' - Stop automatically translating whatever <nick> says."
  (setf (alref nick (alref *channel* (people-to-interpret *bot*))) nil)
  (build-string "Rgr. No longer interpreting for ~A" nick))

(deflistener interpreter-listener
  (let ((output-lang (alref *sender* (alref *channel* (people-to-interpret *bot*)))))
    (when output-lang
      (send-msg *bot* *channel* 
		(build-string "<~A> ~A" *sender*
			      (translate "*" output-lang *message*))))))

(defparameter *language-codes*
  '(("AFRIKAANS" . "af")
    ("ALBANIAN" . "sq")
    ("AMHARIC" . "am")
    ("ARABIC" . "ar")
    ("ARMENIAN" . "hy")
    ("AZERBAIJANI" . "az")
    ("BASQUE" . "eu")
    ("BELARUSIAN" . "be")
    ("BENGALI" . "bn")
    ("BIHARI" . "bh")
    ("BULGARIAN" . "bg")
    ("BURMESE" . "my")
    ("CATALAN" . "ca")
    ("CHEROKEE" . "chr")
    ("CHINESE" . "zh")
    ("CHINESE_SIMPLIFIED" . "zh-CN")
    ("CHINESE_TRADITIONAL" . "zh-TW")
    ("CROATIAN" . "hr")
    ("CZECH" . "cs")
    ("DANISH" . "da")
    ("DHIVEHI" . "dv")
    ("DUTCH" . "nl")  
    ("ENGLISH" . "en")
    ("ESPERANTO" . "eo")
    ("ESTONIAN" . "et")
    ("FILIPINO" . "tl")
    ("FINNISH" . "fi")
    ("FRENCH" . "fr")
    ("GALICIAN" . "gl")
    ("GEORGIAN" . "ka")
    ("GERMAN" . "de")
    ("GREEK" . "el")
    ("GUARANI" . "gn")
    ("GUJARATI" . "gu")
    ("HEBREW" . "iw")
    ("HINDI" . "hi")
    ("HUNGARIAN" . "hu")
    ("ICELANDIC" . "is")
    ("INDONESIAN" . "id")
    ("INUKTITUT" . "iu")
    ("ITALIAN" . "it")
    ("JAPANESE" . "ja")
    ("KANNADA" . "kn")
    ("KAZAKH" . "kk")
    ("KHMER" . "km")
    ("KOREAN" . "ko")
    ("KURDISH" . "ku")
    ("KYRGYZ" . "ky")
    ("LAOTHIAN" . "lo")
    ("LATVIAN" . "lv")
    ("LITHUANIAN" . "lt")
    ("MACEDONIAN" . "mk")
    ("MALAY" . "ms")
    ("MALAYALAM" . "ml")
    ("MALTESE" . "mt")
    ("MARATHI" . "mr")
    ("MONGOLIAN" . "mn")
    ("NEPALI" . "ne")
    ("NORWEGIAN" . "no")
    ("ORIYA" . "or")
    ("PASHTO" . "ps")
    ("PERSIAN" . "fa")
    ("POLISH" . "pl")
    ("PORTUGUESE" . "pt-PT")
    ("PUNJABI" . "pa")
    ("ROMANIAN" . "ro")
    ("RUSSIAN" . "ru")
    ("SANSKRIT" . "sa")
    ("SERBIAN" . "sr")
    ("SINDHI" . "sd")
    ("SINHALESE" . "si")
    ("SLOVAK" . "sk")
    ("SLOVENIAN" . "sl")
    ("SPANISH" . "es")
    ("SWAHILI" . "sw")
    ("SWEDISH" . "sv")
    ("TAJIK" . "tg")
    ("TAMIL" . "ta")
    ("TAGALOG" . "tl")
    ("TELUGU" . "te")
    ("THAI" . "th")
    ("TIBETAN" . "bo")
    ("TURKISH" . "tr")
    ("UKRAINIAN" . "uk")
    ("URDU" . "ur")
    ("UZBEK" . "uz")
    ("UIGHUR" . "ug")
    ("VIETNAMESE" . "vi")
    ("UNKNOWN" . "")))